### PR TITLE
retrieve kubeconfig file after each cluster installation

### LINKED ISSUE #28: Add option to download the kubeconfig after install
We should allow the user to have the kubeconfig automatically downloaded and saved to the cluster install path post install. This can be done via osde2ectl like:

```
$ ./out/osde2ectl --custom-config my_config.yaml get -k -i [my_cluster_id] --kube-config-path /my/test/path/cluster
```

### PR DESCRIPTION
**Pull request by morenod**
After each cluster is installed, kubeconfig file will be downloaded and stored inside the cluster folder, with the rest of the files, creating a new directory for it until [issue on osde2e](https://github.com/openshift/osde2e/issues/657) will be fixed.

```
2020-12-15 16:17:25.794 INFO osde2e-wrapper - _download_kubeconfig: Attempting to load metadata json
2020-12-15 16:17:25.796 INFO osde2e-wrapper - _download_kubeconfig: Downloading kubeconfig file for cluster 1hj6bn6h2qfo4v54cjqkhvv8ds2a7kn6 on /tmp/8a1c5138-e6ac-4e38-a51d-9dec20eba111/1/1hj6bn6h2qfo4v54cjqkhvv8ds2a7kn6
2020-12-15 16:17:25.796 INFO osde2e-wrapper - _download_kubeconfig: Attempting to load metadata json
2020-12-15 16:17:25.802 INFO osde2e-wrapper - _download_kubeconfig: Downloading kubeconfig file for cluster 1hj6bn0sr1tmsa22utah9d73k9e4a7p3 on /tmp/8a1c5138-e6ac-4e38-a51d-9dec20eba111/2/1hj6bn0sr1tmsa22utah9d73k9e4a7p3
2020-12-15 16:17:39.724 INFO osde2e-wrapper - _watcher: Watcher exiting
```

```
$ cd /tmp/8a1c5138-e6ac-4e38-a51d-9dec20eba111/
[morenod@morenod-laptop 8a1c5138-e6ac-4e38-a51d-9dec20eba111]$ ls -l 1/
1hj6bn6h2qfo4v54cjqkhvv8ds2a7kn6/               cluster_account.yaml                            install/                                        test_output.log
1hj6bn6h2qfo4v54cjqkhvv8ds2a7kn6..metrics.prom  custom-prow-metadata.json                       metadata.json                                   
[morenod@morenod-laptop 8a1c5138-e6ac-4e38-a51d-9dec20eba111]$ ls -l 1/1hj6bn6h2qfo4v54cjqkhvv8ds2a7kn6/
total 12
-rwxrwxr-x. 1 morenod morenod 8975 dic 15 16:17 osde2e-hsxri-kubeconfig.txt
[morenod@morenod-laptop 8a1c5138-e6ac-4e38-a51d-9dec20eba111]$ ls -l 2/
1hj6bn0sr1tmsa22utah9d73k9e4a7p3/               cluster_account.yaml                            install/                                        test_output.log
1hj6bn0sr1tmsa22utah9d73k9e4a7p3..metrics.prom  custom-prow-metadata.json                       metadata.json                                   
[morenod@morenod-laptop 8a1c5138-e6ac-4e38-a51d-9dec20eba111]$ ls -l 2/1hj6bn0sr1tmsa22utah9d73k9e4a7p3/
total 12
-rwxrwxr-x. 1 morenod morenod 8975 dic 15 16:17 osde2e-e0ok9-kubeconfig.txt

```

### CODE REVIEW

**Comment by dry923** [comment]
@morenod I recall there was an issue with pulling the kubeconfig to an existing directory w/ osde2ectl. Has that been resolved?

**Comment by morenod** [comment]
> @morenod I recall there was an issue with pulling the kubeconfig to an existing directory w/ osde2ectl. Has that been resolved?

It is still open (and no progress) but it is not affecting this fix, because it includes the creation of a folder to contain the kubeconfig file

**Comment by morenod** [comment]
@dry923 rebased

**Comment by morenod** [comment]
@dry923 re-rebased

**Pull request merged**
