### PR TITLE
Enabling indexing of MC and SC metrics after install

### PR DESCRIPTION
**Pull request by mukrishn**

### CODE REVIEW

**Comment by mukrishn** [comment]
Need this https://github.com/cloud-bulldozer/e2e-benchmarking/pull/532 to be merged before it goes in.

**Comment by mukrishn** [comment]
tested - [install metrics](https://grafana.rdu2.scalelab.redhat.com:3000/d/hcp/hypershift-report-imported?orgId=1&from=1676034308168&to=1676034946208&var-Datasource=AWS%20Pro%20-%20ripsaw-kube-burner&var-mgmt_cluster_name=hs-mc-0vfs0e6gg-.%2A&var-latencyPercentile=P99&var-sdn=OVNKubernetes&var-svc_cluster_name=&var-hosted_cluster_name=mukris-7u5-0001&var-uuid=c2d215f3-40bc-4b06-aa41-6d2c4096f6bc)

**Review by dry923 — APPROVED** [review]
LGTM!

**Comment by dry923** [comment]
@morenod can you take a look at this please

**Review by morenod — APPROVED** [review]
LGTM

**Pull request merged**
