### PR TITLE
Add dependencies required to run rosa-hypershift script

### PR DESCRIPTION
**Pull request by chaitanyaenr**
### Description
List of dependencies/modules added:
- requests
- elasticsearch

### CODE REVIEW

**Comment by chaitanyaenr** [comment]
@dry923 @morenod PTAL. Thanks.

**Comment by morenod** [comment]
elasticsearch is already added on [libs/requirements.txt](https://raw.githubusercontent.com/cloud-bulldozer/perfscale-managed-services/main/libs/requirements.txt) with a fixed version because newer ones are not compatible with AWS ES instance that we are using.

Ok about requests

**Comment by chaitanyaenr** [comment]
@morenod removed elasticsearch from the list. PTAL.

**Review by morenod — APPROVED** [review]
LGTM

**Pull request merged**
