### PR TITLE
Metadata document update with parser

### LINKED ISSUE #53: Update osde2e for new metrics in metadata
A newly built cluster now has additional metadata:

```
# cat /var/jenkins/run-20210204-141221/82/metadata.json 
{"cluster-id": "1ikrg2ioq096pvkruhrs6o7p0btb7blp", "cluster-name": "osde2e-18hgn", "cluster-version": "openshift-v4.6.15", "environment": "prod", "region": "us-east-1", "time-to-ocm-reporting-installed": "1770.729182375", "time-to-cluster-ready": "1740.389981614", "time-to-upgraded-cluster": "0", "time-to-upgraded-cluster-ready": "0", "time-to-certificate-issued": "119.030519994", "install-phase-pass-rate": "-1", "upgrade-phase-pass-rate": "-1", "log-metrics": {"access-token-500": 0, "cluster-mgmt-500": 0, "cluster-pending": 0, "eof": 0, "host-dns-lookup": 0}, "before-suite-metrics": {"AMI ID Retieval Failure": 0, "AWS client creation failure": 0, "AWS credentials not valid": 0, "AWS error due to missing source clusterconfig": 0, "AWS image AMI failure": 0, "AWS region not enabled": 0, "BYOC account vaildation failure": 0, "Error in PollClusterHealth": 0, "Setting osa_use_marketplace_ami property manually": 0, "Test Panicked due to runtime error": 0, "cluster-health-check": 0, "cluster-install timeout": 0, "cluster-retrieval OCM error": 0, "cluster-setup": 0, "error creating cluster": 0, "failed to get access keys for user 'osdCcsAdmin'": 0, "missing quota for cluster creation": 0, "quota-check": 0, "running task Updating Alertmanager failed": 0, "timed out waiting for the condition during syncRequiredMachineConfigPools": 0}, "route-latencies": {}, "route-throughputs": {}, "route-availabilities": {}, "healthchecks": {}, "healthcheckIteration": 118, "status": "ready", "cluster_start_time": "2021-02-04T14:34:49", "cluster_end_time": "2021-02-04T15:38:13", "install_successful": true, "uuid": "98f26b1d-faaf-4894-ac22-0a5383849b78", "install_counter": 82}
```

We should look through the newly added information and decide what makes sense to add to the ES doc

### PR DESCRIPTION
**Pull request by chentex**
Adds ability to parse the metadata json file.

This will generate the ES document to be stored.
Adds the ability to ignore metadata by key name.
Adds unit tests for new functions.

supersedes #58 
fixes #53 

Signed-off-by: Vicente Zepeda Mas <vzepedam@redhat.com>

### CODE REVIEW

**Comment by chentex** [comment]
I added an argument `--ignored-metadata` that can receive a list of keys to ignore. It is set to default to [this list.](https://github.com/cloud-bulldozer/perfscale-managed-services/issues/53#issuecomment-775279123)

This is a document with the default ignore list in place
```
{"cluster_id":"1io685sats9ig0mla6ljdvovk9qo7dit","cluster_name":"osde2e-z8j-0001","cluster_version":"openshift-v4.5.13","environment":"stage","region":"us-west-1","time_to_ocm_reporting_installed":2130,"time_to_cluster_ready":1682,"time_to_upgraded_cluster":0,"time_to_upgraded_cluster_ready":0,"time_to_certificate_issued":119,"install_phase_pass_rate":-1,"upgrade_phase_pass_rate":-1,"log_metrics":{"access_token_500":0,"cluster_mgmt_500":0,"cluster_pending":1,"eof":0,"host_dns_lookup":0},"cluster_start_time":"2021-02-09T17:02:28","cluster_end_time":"2021-02-09T18:08:29","install_successful":true,"uuid":"21d214e4-a5f7-4b80-8890-0a10d0406e7e","install_counter":1,"timestamp":"2021-02-09T18:08:30"}|
```

This is a document that only received this as an argument `--ignored-metadata status`.

```
{"cluster_id":"1io503fmer8gc52t63ad64hd6k55ege4","cluster_name":"osde2e-jlz-0001","cluster_version":"openshift-v4.5.13","environment":"stage","region":"us-west-1","time_to_ocm_reporting_installed":1831,"time_to_cluster_ready":2011,"time_to_upgraded_cluster":0,"time_to_upgraded_cluster_ready":0,"time_to_certificate_issued":118,"install_phase_pass_rate":-1,"upgrade_phase_pass_rate":-1,"log_metrics":{"access_token_500":0,"cluster_mgmt_500":0,"cluster_pending":1,"eof":1,"host_dns_lookup":0},"before_suite_metrics":{"ami_id_retieval_failure":0,"aws_client_creation_failure":0,"aws_credentials_not_valid":0,"aws_error_due_to_missing_source_clusterconfig":0,"aws_image_ami_failure":0,"aws_region_not_enabled":0,"byoc_account_vaildation_failure":0,"error_in_pollclusterhealth":7,"setting_osa_use_marketplace_ami_property_manually":0,"test_panicked_due_to_runtime_error":0,"cluster_health_check":0,"cluster_install_timeout":60,"cluster_retrieval_ocm_error":0,"cluster_setup":0,"error_creating_cluster":0,"failed_to_get_access_keys_for_user_'osdccsadmin'":0,"missing_quota_for_cluster_creation":0,"quota_check":0,"running_task_updating_alertmanager_failed":0,"timed_out_waiting_for_the_condition_during_syncrequiredmachineconfigpools":0},"route_latencies":{},"route_throughputs":{},"route_availabilities":{},"healthchecks":{},"healthcheckiteration":129,"cluster_start_time":"2021-02-09T15:36:59","cluster_end_time":"2021-02-09T16:43:25","install_successful":true,"uuid":"afa5f582-3d68-483b-9c97-efef7ee89072","install_counter":1,"timestamp":"2021-02-09T16:43:26"}
```

Any thoughts  @dry923 @morenod ?

**Comment by morenod** [comment]
I like it, but can you add a --es- to the parameter as any other elásticsearch related arguments?

**Comment by chentex** [comment]
> I like it, but can you add a --es- to the parameter as any other elásticsearch related arguments?

Sounds good, I have done the change.

**Review by morenod — APPROVED** [review]
LGTM

**Pull request merged**
