### PR TITLE
move some outputs to debug

### LINKED ISSUE #20: Change some logging to debug
We have some command output being given as info when it should likely be in debug. Particularly during the thread creation. We should trim the info down to something like "Starting cluster X"

```
2020-12-01 15:34:32.624 INFO osde2e-wrapper - _build_cluster: Attempting cluster installation
2020-12-01 15:34:32.624 INFO osde2e-wrapper - _build_cluster: Output directory set to /osde2e/dec_1/329
2020-12-01 15:34:47.635 INFO osde2e-wrapper - main: Starting Cluster thread 331
```

### PR DESCRIPTION
**Pull request by morenod**
Info execution:

```
$ python3 osde2e-scale-wrapper/osde2e-wrapper.py --account-config /home/morenod/osd/custom_config.yaml --cluster-count 10 --command /home/morenod/osd/osde2e/out --log-level info
2021-01-05 12:47:32.004 INFO osde2e-wrapper - main: Logging to console
2021-01-05 12:47:32.005 INFO osde2e-wrapper - main: Test running with UUID: 7d019831-f064-45e3-ab6b-0ca427c1ad96
2021-01-05 12:47:32.005 INFO osde2e-wrapper - main: Using /tmp/7d019831-f064-45e3-ab6b-0ca427c1ad96 as temp directory
2021-01-05 12:47:32.005 INFO osde2e-wrapper - _create_path: Create directory /tmp/7d019831-f064-45e3-ab6b-0ca427c1ad96 if it does not exist
2021-01-05 12:47:32.014 INFO osde2e-wrapper - main: User override set to: dsanzmor
2021-01-05 12:47:32.014 INFO osde2e-wrapper - _verify_cmnd: Testing osde2e command with: osde2e -h
2021-01-05 12:47:32.166 INFO osde2e-wrapper - _verify_cmnd: osde2e and osde2ectl commands validated with -h. Directory is /home/morenod/osd/osde2e/out
2021-01-05 12:47:32.167 INFO osde2e-wrapper - main: Launching watcher thread
2021-01-05 12:47:32.167 INFO osde2e-wrapper - _watcher: Watcher thread started
2021-01-05 12:47:32.167 INFO osde2e-wrapper - _watcher: Getting status every 60 seconds
2021-01-05 12:47:32.167 INFO osde2e-wrapper - main: Attempting to start 10 clusters with 0 batch size
2021-01-05 12:47:32.182 INFO osde2e-wrapper - _build_cluster: Started cluster 1
2021-01-05 12:47:32.219 INFO osde2e-wrapper - main: All clusters (10) requested. Waiting for them to finish
2021-01-05 12:47:32.257 INFO osde2e-wrapper - _build_cluster: Started cluster 3
2021-01-05 12:47:32.264 INFO osde2e-wrapper - _build_cluster: Started cluster 2
2021-01-05 12:47:32.297 INFO osde2e-wrapper - _build_cluster: Started cluster 7
2021-01-05 12:47:32.336 INFO osde2e-wrapper - _build_cluster: Started cluster 6
2021-01-05 12:47:32.342 INFO osde2e-wrapper - _build_cluster: Started cluster 10
2021-01-05 12:47:32.350 INFO osde2e-wrapper - _build_cluster: Started cluster 4
2021-01-05 12:47:32.356 INFO osde2e-wrapper - _build_cluster: Started cluster 5
2021-01-05 12:47:32.357 INFO osde2e-wrapper - _build_cluster: Started cluster 9
2021-01-05 12:47:32.366 INFO osde2e-wrapper - _build_cluster: Started cluster 8
2021-01-05 12:47:40.484 INFO osde2e-wrapper - _watcher: Requested Clusters: 10
2021-01-05 12:47:40.484 INFO osde2e-wrapper - _watcher: Current state counts:
2021-01-05 12:47:40.484 INFO osde2e-wrapper - _watcher: dict_items([('installing', 10)])
2021-01-05 12:47:40.485 INFO osde2e-wrapper - _watcher: Current status counts:
2021-01-05 12:47:40.485 INFO osde2e-wrapper - _watcher: dict_items([('waiting-for-ready', 10)])
2021-01-05 12:47:40.485 INFO osde2e-wrapper - _watcher: Clusters in error state:
2021-01-05 12:47:40.485 INFO osde2e-wrapper - _watcher: []
2021-01-05 12:48:51.908 INFO osde2e-wrapper - _watcher: Requested Clusters: 20
2021-01-05 12:48:51.908 INFO osde2e-wrapper - _watcher: Current state counts:
2021-01-05 12:48:51.909 INFO osde2e-wrapper - _watcher: dict_items([('installing', 18), ('pending', 2)])
2021-01-05 12:48:51.909 INFO osde2e-wrapper - _watcher: Current status counts:
2021-01-05 12:48:51.909 INFO osde2e-wrapper - _watcher: dict_items([('waiting-for-ready', 20)])
2021-01-05 12:48:51.909 INFO osde2e-wrapper - _watcher: Clusters in error state:
2021-01-05 12:48:51.909 INFO osde2e-wrapper - _watcher: []
```

Debug execution:

```$ python3 osde2e-scale-wrapper/osde2e-wrapper.py --account-config /home/morenod/osd/custom_config.yaml --cluster-count 10 --command /home/morenod/osd/osde2e/out --log-level debug
2021-01-05 13:00:44.966 INFO osde2e-wrapper - main: Logging to console
2021-01-05 13:00:44.966 INFO osde2e-wrapper - main: Test running with UUID: 3067cac4-cbb5-4f7f-a3ab-6a06a7db052a
2021-01-05 13:00:44.966 INFO osde2e-wrapper - main: Using /tmp/3067cac4-cbb5-4f7f-a3ab-6a06a7db052a as temp directory
2021-01-05 13:00:44.966 INFO osde2e-wrapper - _create_path: Create directory /tmp/3067cac4-cbb5-4f7f-a3ab-6a06a7db052a if it does not exist
2021-01-05 13:00:44.967 DEBUG osde2e-wrapper - main: Account configuration file exists
2021-01-05 13:00:44.974 INFO osde2e-wrapper - main: User override set to: dsanzmor
2021-01-05 13:00:44.974 INFO osde2e-wrapper - _verify_cmnd: Testing osde2e command with: osde2e -h
2021-01-05 13:00:45.085 INFO osde2e-wrapper - _verify_cmnd: osde2e and osde2ectl commands validated with -h. Directory is /home/morenod/osd/osde2e/out
2021-01-05 13:00:45.085 INFO osde2e-wrapper - main: Launching watcher thread
2021-01-05 13:00:45.086 INFO osde2e-wrapper - _watcher: Watcher thread started
2021-01-05 13:00:45.086 INFO osde2e-wrapper - main: Attempting to start 10 clusters with 0 batch size
2021-01-05 13:00:45.086 INFO osde2e-wrapper - _watcher: Getting status every 60 seconds
2021-01-05 13:00:45.086 DEBUG osde2e-wrapper - main: Starting Cluster thread 2
2021-01-05 13:00:45.087 DEBUG osde2e-wrapper - main: Number of alive threads 3
2021-01-05 13:00:45.087 DEBUG osde2e-wrapper - main: Starting Cluster thread 3
2021-01-05 13:00:45.088 DEBUG osde2e-wrapper - main: Number of alive threads 4
2021-01-05 13:00:45.088 DEBUG osde2e-wrapper - main: Starting Cluster thread 4
2021-01-05 13:00:45.089 DEBUG osde2e-wrapper - main: Number of alive threads 5
2021-01-05 13:00:45.090 DEBUG osde2e-wrapper - main: Starting Cluster thread 5
2021-01-05 13:00:45.090 DEBUG osde2e-wrapper - main: Number of alive threads 6
2021-01-05 13:00:45.091 DEBUG osde2e-wrapper - main: Starting Cluster thread 6
2021-01-05 13:00:45.091 DEBUG osde2e-wrapper - main: Number of alive threads 7
2021-01-05 13:00:45.092 DEBUG osde2e-wrapper - main: Starting Cluster thread 7
2021-01-05 13:00:45.116 DEBUG osde2e-wrapper - _build_cluster: Attempting cluster installation
2021-01-05 13:00:45.116 DEBUG osde2e-wrapper - _build_cluster: Output directory set to /tmp/3067cac4-cbb5-4f7f-a3ab-6a06a7db052a/5
2021-01-05 13:00:45.117 DEBUG osde2e-wrapper - main: Number of alive threads 8
2021-01-05 13:00:45.118 DEBUG osde2e-wrapper - main: Starting Cluster thread 8
2021-01-05 13:00:45.123 DEBUG osde2e-wrapper - main: Number of alive threads 9
2021-01-05 13:00:45.124 DEBUG osde2e-wrapper - main: Starting Cluster thread 9
2021-01-05 13:00:45.130 DEBUG osde2e-wrapper - main: Number of alive threads 10
2021-01-05 13:00:45.131 DEBUG osde2e-wrapper - main: Starting Cluster thread 10
2021-01-05 13:00:45.137 INFO osde2e-wrapper - _build_cluster: Started cluster 5
2021-01-05 13:00:45.137 DEBUG osde2e-wrapper - _build_cluster: Attempting cluster installation
2021-01-05 13:00:45.141 DEBUG osde2e-wrapper - _watcher: ['/home/morenod/osd/osde2e/out/osde2ectl', 'list', '--custom-config', 'account_config.yaml']
2021-01-05 13:00:45.149 DEBUG osde2e-wrapper - _build_cluster: Attempting cluster installation
2021-01-05 13:00:45.150 DEBUG osde2e-wrapper - main: Number of alive threads 11
2021-01-05 13:00:45.155 DEBUG osde2e-wrapper - _build_cluster: Attempting cluster installation
2021-01-05 13:00:45.160 DEBUG osde2e-wrapper - _build_cluster: Attempting cluster installation
2021-01-05 13:00:45.165 DEBUG osde2e-wrapper - _build_cluster: Attempting cluster installation
2021-01-05 13:00:45.171 DEBUG osde2e-wrapper - _build_cluster: Output directory set to /tmp/3067cac4-cbb5-4f7f-a3ab-6a06a7db052a/3
2021-01-05 13:00:45.172 DEBUG osde2e-wrapper - _build_cluster: Output directory set to /tmp/3067cac4-cbb5-4f7f-a3ab-6a06a7db052a/7
2021-01-05 13:00:45.178 DEBUG osde2e-wrapper - _build_cluster: Attempting cluster installation
2021-01-05 13:00:45.178 DEBUG osde2e-wrapper - _build_cluster: Attempting cluster installation
2021-01-05 13:00:45.179 DEBUG osde2e-wrapper - main: Starting Cluster thread 11
2021-01-05 13:00:45.179 DEBUG osde2e-wrapper - _build_cluster: Output directory set to /tmp/3067cac4-cbb5-4f7f-a3ab-6a06a7db052a/1
2021-01-05 13:00:45.181 DEBUG osde2e-wrapper - _build_cluster: Output directory set to /tmp/3067cac4-cbb5-4f7f-a3ab-6a06a7db052a/4
2021-01-05 13:00:45.181 DEBUG osde2e-wrapper - _build_cluster: Output directory set to /tmp/3067cac4-cbb5-4f7f-a3ab-6a06a7db052a/2
2021-01-05 13:00:45.182 DEBUG osde2e-wrapper - _build_cluster: Output directory set to /tmp/3067cac4-cbb5-4f7f-a3ab-6a06a7db052a/6
2021-01-05 13:00:45.194 DEBUG osde2e-wrapper - _build_cluster: Output directory set to /tmp/3067cac4-cbb5-4f7f-a3ab-6a06a7db052a/8
2021-01-05 13:00:45.198 DEBUG osde2e-wrapper - main: Number of alive threads 12
2021-01-05 13:00:45.241 INFO osde2e-wrapper - main: All clusters (10) requested. Waiting for them to finish
2021-01-05 13:00:45.206 INFO osde2e-wrapper - _build_cluster: Started cluster 7
2021-01-05 13:00:45.207 DEBUG osde2e-wrapper - _build_cluster: Attempting cluster installation
2021-01-05 13:00:45.245 DEBUG osde2e-wrapper - _build_cluster: Output directory set to /tmp/3067cac4-cbb5-4f7f-a3ab-6a06a7db052a/9
2021-01-05 13:00:45.201 INFO osde2e-wrapper - _build_cluster: Started cluster 3
2021-01-05 13:00:45.244 DEBUG osde2e-wrapper - _build_cluster: Attempting cluster installation
2021-01-05 13:00:45.251 DEBUG osde2e-wrapper - _build_cluster: Output directory set to /tmp/3067cac4-cbb5-4f7f-a3ab-6a06a7db052a/10
2021-01-05 13:00:45.245 INFO osde2e-wrapper - _build_cluster: Started cluster 4
2021-01-05 13:00:45.219 INFO osde2e-wrapper - _build_cluster: Started cluster 1
2021-01-05 13:00:45.249 INFO osde2e-wrapper - _build_cluster: Started cluster 8
2021-01-05 13:00:45.250 INFO osde2e-wrapper - _build_cluster: Started cluster 6
2021-01-05 13:00:45.245 INFO osde2e-wrapper - _build_cluster: Started cluster 2
2021-01-05 13:00:45.273 INFO osde2e-wrapper - _build_cluster: Started cluster 9
2021-01-05 13:00:45.291 INFO osde2e-wrapper - _build_cluster: Started cluster 10
2021-01-05 13:00:51.706 INFO osde2e-wrapper - _watcher: Requested Clusters: 7
```

### CODE REVIEW

**Comment by dry923** [comment]
Good work @morenod ! Do you think the watcher start lines should also be in debug?
```
    logging.info('Watcher thread started')
    logging.info('Getting status every %d seconds' % int(delay))
```

**Comment by morenod** [comment]
> Good work @morenod ! Do you think the watcher start lines should also be in debug?
> 
> ```
>     logging.info('Watcher thread started')
>     logging.info('Getting status every %d seconds' % int(delay))
> ```

As it is not being repeated, im fine on getting in on info, as it is going to be showed only one time.

Im thinking about how to reduce lines on watcher execution, maybe we could parse better the status and state and move to oneliner, from:

```
2021-01-05 13:36:52.062 INFO osde2e-wrapper - _watcher: Requested Clusters: 10
2021-01-05 13:36:52.063 INFO osde2e-wrapper - _watcher: Current state counts:
2021-01-05 13:36:52.063 INFO osde2e-wrapper - _watcher: dict_items([('ready', 7), ('error', 1), ('installing', 2)])
2021-01-05 13:36:52.063 INFO osde2e-wrapper - _watcher: Current status counts:
2021-01-05 13:36:52.063 INFO osde2e-wrapper - _watcher: dict_items([('operator,pod', 6), ('cvo,operator,pod', 1), ('waiting-for-ready', 3)])
2021-01-05 13:36:52.063 INFO osde2e-wrapper - _watcher: Clusters in error state:
2021-01-05 13:36:52.063 INFO osde2e-wrapper - _watcher: ['1i10dsca5gdglp3qssvjnstjckh28kfq']
```

to something like:

```
2021-01-05 13:36:52.062 INFO osde2e-wrapper - _watcher: Current state: 10 clusters (7 ready) (1 error) (2 installing)
2021-01-05 13:36:52.063 INFO osde2e-wrapper - _watcher: Current status counts: 10 clusters (6 'operator,pod') (1 'cvo,operator,pod') (3 'waiting-for-ready')
2021-01-05 13:36:52.063 DEBUG osde2e-wrapper - _watcher: Clusters in error state:
2021-01-05 13:36:52.063 DEBUG osde2e-wrapper - _watcher: ['1i10dsca5gdglp3qssvjnstjckh28kfq']
```

From 7 lines to 3 (+2 DEBUG)

**Comment by dry923** [comment]
> > Good work @morenod ! Do you think the watcher start lines should also be in debug?
> > ```
> >     logging.info('Watcher thread started')
> >     logging.info('Getting status every %d seconds' % int(delay))
> > ```
> 
> As it is not being repeated, im fine on getting in on info, as it is going to be showed only one time.
> 
> Im thinking about how to reduce lines on watcher execution, maybe we could parse better the status and state and move to oneliner, from:
> 
> ```
> 2021-01-05 13:36:52.062 INFO osde2e-wrapper - _watcher: Requested Clusters: 10
> 2021-01-05 13:36:52.063 INFO osde2e-wrapper - _watcher: Current state counts:
> 2021-01-05 13:36:52.063 INFO osde2e-wrapper - _watcher: dict_items([('ready', 7), ('error', 1), ('installing', 2)])
> 2021-01-05 13:36:52.063 INFO osde2e-wrapper - _watcher: Current status counts:
> 2021-01-05 13:36:52.063 INFO osde2e-wrapper - _watcher: dict_items([('operator,pod', 6), ('cvo,operator,pod', 1), ('waiting-for-ready', 3)])
> 2021-01-05 13:36:52.063 INFO osde2e-wrapper - _watcher: Clusters in error state:
> 2021-01-05 13:36:52.063 INFO osde2e-wrapper - _watcher: ['1i10dsca5gdglp3qssvjnstjckh28kfq']
> ```
> 
> to something like:
> 
> ```
> 2021-01-05 13:36:52.062 INFO osde2e-wrapper - _watcher: Current state: 10 clusters (7 ready) (1 error) (2 installing)
> 2021-01-05 13:36:52.063 INFO osde2e-wrapper - _watcher: Current status counts: 10 clusters (6 'operator,pod') (1 'cvo,operator,pod') (3 'waiting-for-ready')
> 2021-01-05 13:36:52.063 DEBUG osde2e-wrapper - _watcher: Clusters in error state:
> 2021-01-05 13:36:52.063 DEBUG osde2e-wrapper - _watcher: ['1i10dsca5gdglp3qssvjnstjckh28kfq']
> ```
> 
> From 7 lines to 3 (+2 DEBUG)

Makes sense. I like that change however I'd say the error state ones should be info or warning as they are arguably more important that the other status as there might be action needed to investigate.

**Comment by morenod** [comment]
yeah, totally agree, I will work on it and add them as warning

**Comment by morenod** [comment]
@dry923 New output on watcher section

```
2021-01-05 18:04:46.404 INFO osde2e-wrapper - _watcher: Current clusters state: 10 clusters (pending: 5) (installing: 4) (error: 1)
2021-01-05 18:04:46.404 INFO osde2e-wrapper - _watcher: Current clusters status: 10 clusters (waiting-for-ready: 10)
2021-01-05 18:04:46.405 WARNING osde2e-wrapper - _watcher: Clusters in error state: ['1i14rq2gtvolcs1narcqbqhkbf4hqb8c']
2021-01-05 18:05:52.905 INFO osde2e-wrapper - _watcher: Current clusters state: 10 clusters (installing: 9) (error: 1)
2021-01-05 18:05:52.905 INFO osde2e-wrapper - _watcher: Current clusters status: 10 clusters (waiting-for-ready: 10)
2021-01-05 18:05:52.905 WARNING osde2e-wrapper - _watcher: Clusters in error state: ['1i14rq2gtvolcs1narcqbqhkbf4hqb8c']
2021-01-05 18:06:59.362 INFO osde2e-wrapper - _watcher: Current clusters state: 10 clusters (installing: 9) (error: 1)
2021-01-05 18:06:59.362 INFO osde2e-wrapper - _watcher: Current clusters status: 10 clusters (waiting-for-ready: 10)
2021-01-05 18:06:59.363 WARNING osde2e-wrapper - _watcher: Clusters in error state: ['1i14rq2gtvolcs1narcqbqhkbf4hqb8c']
2021-01-05 18:08:07.622 INFO osde2e-wrapper - _watcher: Current clusters state: 10 clusters (installing: 9) (error: 1)
2021-01-05 18:08:07.623 INFO osde2e-wrapper - _watcher: Current clusters status: 10 clusters (waiting-for-ready: 10)
2021-01-05 18:08:07.623 WARNING osde2e-wrapper - _watcher: Clusters in error state: ['1i14rq2gtvolcs1narcqbqhkbf4hqb8c']
2021-01-05 18:09:13.537 INFO osde2e-wrapper - _watcher: Current clusters state: 10 clusters (installing: 9) (error: 1)
2021-01-05 18:09:13.537 INFO osde2e-wrapper - _watcher: Current clusters status: 10 clusters (waiting-for-ready: 10)
2021-01-05 18:09:13.537 WARNING osde2e-wrapper - _watcher: Clusters in error state: ['1i14rq2gtvolcs1narcqbqhkbf4hqb8c']
```

**Pull request merged**
