### PR TITLE
Allows creating roles with latest-policies

### PR DESCRIPTION
**Pull request by krishvoor**
This PR allows to enforce latest-policies

Signed-off-by: Krishna Harsha Voora <krvoora@redhat.com>

### CODE REVIEW

**Comment by krishvoor** [comment]
@dry923 @morenod ptal

**Comment by morenod** [comment]
Do you have a doc link for this requirement? roles creation has been always included in the rosa create cluster command, why is now required to pre-execute it?

If it is really required, and cluster install will fail if this command fails, we need to capture command return code, and manage it to break installation or not

**Comment by krishvoor** [comment]
This was reported here
https://redhat-internal.slack.com/archives/C04EUL1DRHC/p1677855396643189?thread_ts=1677855396.643189&cid=C04EUL1DRHC 

Gist of this PR, despite on latest rosa-cli GA branch, the latest policies were not in effect, as a result, HCP didn't had get any awsmachine worker pool, upon applying these changes, the nodepool came up properly.

**Comment by morenod** [comment]
Is this something to be executed before or after cluster is created? 

I see two commands on the slack chat:

`rosa create account-roles` which is actually being executed, but not added on the scripts, because it is only required one time just before start creating clusters on aws (or when policies changes)

`rosa create operator roles -c <cluster_id> -m auto -y -f` which seems to be executed **after** cluster is installed, as it requires the ClusterID as parameter.

This is the same command you want to add to the script, but before cluster is installed, is that right?

Can you paste some log of this code execution?

**Comment by dry923** [comment]
+1 to @morenod 's comment re the timing of when it needs to be created and also I'm concerned that this is only ever creating new policy's but never cleaning them up

**Comment by krishvoor** [comment]
@dry923 @morenod Agreed, this should happen post-creation of cluster.

>Can you paste some log of this code execution?

I'll be sure to get you the logs.

>I'm concerned that this is only ever creating new policy's but never cleaning them up

We are already cleaning  them here:
https://github.com/cloud-bulldozer/perfscale-managed-services/blob/main/rosa-hypershift/rosa-hosted-wrapper.py#L955

**Comment by krishvoor** [comment]
This can be closed..

**Pull request closed without merging**
